GET https://malavivikas.github.io/books/db.json/books HTTP/1.1
Content-Type: application/json

###

POST https://malavivikas.github.io/books/db.json/books HTTP/1.1
Content-Type: application/json

{
    "title": "Harry Potter"
}

###

PUT https://malavivikas.github.io/books/db.json/books/1 HTTP/1.1
Content-Type: application/json

{
    "title": "Dark Tower"
}

###

DELETE https://malavivikas.github.io/books/db.json/books/1 HTTP/1.1
Content-Type: application/json